apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
    name: kafka
spec:
    kafka:
        config:
            auto.create.topics.enable: true
            log.retention.bytes: 1073741824
            log.retention.hours: 1
            log.retention.check.interval.ms: 300000
            offsets.topic.replication.factor: 1
            transaction.state.log.min.isr: 1
            transaction.state.log.replication.factor: 1
        listeners:
            plain: {}
            tls: {}
        replicas: 2
        storage:
            size: 1Gi
            type: persistent-claim
            class: local
        version: 2.5.1
    zookeeper:
        replicas: 3
        resources: {}
        storage:
            size: 10Gi
            type: persistent-claim
            class: local
