apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: cmak
    namespace: default
spec:
    chart:
        repository: https://github.com/yahoo/CMAK
        name: cmak
        version: 3.0.0.5
