apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: strimzi-kafka-operator
    namespace: default
spec:
    releaseName: strimzi-kafka-operator
    chart:
        repository: https://strimzi.io/charts/
        name: strimzi-kafka-operator
        version: 0.22.1
