apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: strimzi
    namespace: default
spec:
    releaseName: strimzi
    chart:
        repository: https://strimzi.io/charts/
        name: strimzi
        version: 0.22.1
